fix: don't require full Xcode when installing stable release
Trying to install the stable release results in this error:

> brew install socktainer
==> Fetching downloads for: socktainer
socktainer: A full installation of Xcode.app 26.0 is required to compile
this software. Installing just the Command Line Tools is not sufficient.

Xcode can be installed from the App Store.
Error: socktainer: An unsatisfied requirement failed this build.

Adding a build condition to the Xcode dependency resolved the issue.
Successfully tested on my laptop by editing the formula and installing
it afterwards.

Signed-off-by: Olivier Ligot <oligot@protonmail.com>